### ISSUE TITLE
Files without calendar.txt or calendar_dates.txt cannot be loaded.

### ISSUE THREAD

**Issue by MattBurb** [ShadowFoxNixill/GTFS-Explorer#1]
This happens with GTFS feeds that lack one or both of these files, no matter what. For example, the Amtrak GTFS feed, which I got from here: http://github.com/transitland/gtfs-archives-not-hosted-elsewhere/raw/master/amtrak.zip

Is there a workaround or fix for this? Thanks.

**Comment by Nixill** [comment]
Correct behavior is that if a GTFS feed lacks both `calendar.txt` *AND* `calendar_dates.txt`, the feed can't be loaded—feeds must have at least one of these files to establish the days that trips run.

However, you're correct in that the explorer is failing to load feeds that are missing *either* of these files. A fix will be out shortly.

In the meantime, you can work around it in the current version by adding an empty `calendar.txt` or `calendar_dates.txt` file to the feed, as appropriate. Those files are attached here. For the Amtrak feed you linked, you'll want to add `calendar_dates.txt`.

[calendar.txt](https://github.com/ShadowFoxNixill/GTFS-Explorer/files/6410030/calendar.txt)
[calendar_dates.txt](https://github.com/ShadowFoxNixill/GTFS-Explorer/files/6410031/calendar_dates.txt)

**Comment by Nixill** [comment]
And the fixed version is [released](https://github.com/ShadowFoxNixill/GTFS-Explorer/releases/tag/v0.1.1)! This was a simple bug, but I also found a couple others now that I have the ability to actually test for them, so it probably won't be the last release of the day.
